apiVersion: v1
kind: Pod
metadata:
  name: {{ include "busybox-chart.fullname" . }}
  labels:
    {{- include "busybox-chart.labels" . | nindent 4 }}
spec:
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      command: ["/bin/sh", "-c"]
      args: ["while true; do echo Hello from BusyBox; sleep 5; done"]