apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.postDeployMessage }}
  labels:
    app: busybox-pod
spec:
  containers:
    - name: busybox-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args: ["while true; do echo hi; sleep 5; done"]